name: 04 - Uso de Actions
on: workflow_dispatch
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: 'Checkout Code'          
         uses: actions/checkout@v4
         
       - name: 'Node Setup'
         uses: actions/setup-node@v4
         with:
           node-version: '24.x'

       - name: 'Install Dependencies'
         working-directory: ./my-app
         run: |            
            npm ci

       - name: 'Run Unit Tests'
         working-directory: ./my-app
         run: |            
            npm run test