name: 10 - Functions
on: 
  pull_request: 
  workflow_dispatch: 
    inputs:
      env_selector:
        description: 'environment selector'
        type: environment
        required: true

        
jobs:
    demo:
       runs-on: ubuntu-latest
       environment: ${{ inputs.env_selector }}
       steps:
         - name: Bug step
           if: ${{contains(github.event.pull_request.title,'fix')}}
           run: echo "Bug fix detected"
         - name: Failing step
           run: exit 0
         - name: Paso intermedio
           run: echo "Hola Pepito"  
         - name: Run on success
           if: success()
           run: echo "Success step"
         - name: Run on failure
           if: failure() 
           run: echo "Failure step"
         - name: Always step
           if: always()
           run: echo "Always step" 